# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
